CREATE TABLE IF NOT EXISTS messages(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INT NOT NULL,
  date DATETIME NOT NULL,
  topic TEXT NOT NULL,
  priority INT NOT NULL,
  details TEXT,
  archived BOOLEAN NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE IF NOT EXISTS user(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(50) NOT NULL,
  token VARCHAR(128) NOT NULL,
  created DATETIME NOT NULL,
  activated BOOLEAN NOT NULL,
  UNIQUE (name)
);